### ISSUE TITLE
can't debug in nebula-dev:centos7

### ISSUE THREAD

**Issue by rainboat2** [vesoft-inc/nebula-dev-docker#60]
I compile the debug version of  nebula in nebula-dev:centos:7 container successfully, but when I try to debug it using the default gdb, it failed and got the following information.

```
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Traceback (most recent call last):
  File "<string>", line 144, in <module>
AttributeError: 'module' object has no attribute 'printing'
Traceback (most recent call last):
  File "<string>", line 4, in <module>
gdb.error: /etc/gdbinit.d/nebula.gdb:294: Error in sourced command file:
Error while executing Python code.
/etc/gdbinit:9: Error in sourced command file:
Error while executing Python code.
attach: No such file or directory.
Attaching to process 2526
Reading symbols from /root/nebula-graph/install/debug/bin/nebula-graphd...Dwarf Error: wrong version in compilation unit header (is 0, should be 2, 3, or 4) [in module /root/nebula-graph/install/debug/bin/nebula-graphd]
(no debugging symbols found)...done.
Reading symbols from /lib64/libresolv.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libresolv.so.2
Reading symbols from /lib64/libdl.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/libdl.so.2
Reading symbols from /lib64/libm.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libm.so.6
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
[New LWP 3112]
...
[New LWP 2527]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2
0x00007fee28cb90e3 in epoll_wait () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-325.el7_9.x86_64
```

Maybe it is the default gdb is incompatible with the nebula graph that cause this problem. Could you supply a compatible gdb in the nebula-dev:centos7 images?

**Comment by Anna521** [comment]
Did you slove this problem?

**Comment by Shinji-IkariG** [comment]
Nebula supports the gdb that comes with the system. Since the problem is too old, if you encounter any problems with gdb, please submit the log

**Comment by QingZ11** [comment]
We have noticed that the issue you created hasn’t been updated for nearly a month, is this issue been resolved? If not resolved, can you provide some more information? If solved, can you close this issue?

Thanks a lot for your contribution anyway 😊
